baseURL = "https://chrisulloa.github.io/"
languageCode = "en-us"
title = "Christian Gonzalez"
theme ="noteworthy"
paginate = 4
summaryLength = 10

[author]
    name = "chrisulloa"
[markup.goldmark.renderer]
    unsafe = true
[params]
    description = "Things on my mind..."
    email = "mailto:chrisulloago@gmail.com"
    linkedin = "https://www.linkedin.com/in/chrisulloa/"
    github = "https://github.com/chrisulloa"
    instagram = "https://instagram.com/chrisulloa"
[[menu.main]]
    name = "Posts"
    identifier = "posts"
    url = "/posts/"
    weight = 1
[[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2
