baseURL = "https://chrisulloa.github.io/"
languageCode = "en-us"
title = "Christian Gonzalez"
theme ="noteworthy"
paginate = 4
summaryLength = 10

[author]
    name = "chrisulloa"
[params]
email = "mailto:chrisulloago@gmail.com"
linkedin = "https://www.linkedin.com/in/chrisulloa/"
github = "https://github.com/chrisulloa"
instagram = "https://instagram.com/chrisulloa"

[[menu.main]]
    identifier = "about"
    name = "About Me"
    url = "/about/"
    weight = 1

[[menu.main]]
    name = "Posts"
    identifier = "posts"
    url = "/"
